- name: Install Osquery on Linux
  hosts: 'osquery_linux'
  tasks:
    - name: Get Kolide cert and enroll key
      ansible.builtin.import_tasks: 'roles/osquery/init.yml'
      delegate_to: localhost
      run_once: true # noqa: run-once[task]

    - name: Install Osquery on Linux
      ansible.builtin.import_tasks: 'roles/osquery/linux/setup_osquery.yml'
      become: true
      become_user: root
