- name: Install Osquery on Windows
  hosts: 'osquery_windows'
  tasks:
    - name: Get Kolide cert and enroll key
      ansible.builtin.import_tasks: 'roles/osquery/init.yml'
      delegate_to: localhost
      run_once: true # noqa: run-once[task]

    - name: Install Osquery on Windows
      ansible.builtin.import_tasks: 'roles/osquery/windows/setup_osquery.yml'
