####################################################################
# Apt update
####################################################################
- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: true

####################################################################
#  Setup Timedatectl
####################################################################
- name: Set time to {{ timezone }}
  ansible.builtin.shell: timedatectl set-ntp on && timedatectl set-timezone {{ timezone }}

####################################################################
#  Setup Firewall
####################################################################
- name: Setup Ubuntu UFW firewall
  community.general.ufw:
    rule: allow
    name: OpenSSH
- community.general.ufw:
    rule: allow
    port: 80
    proto: tcp
- community.general.ufw:
    rule: allow
    port: 443
    proto: tcp
- community.general.ufw:
    state: enabled
    policy: deny
