- hosts: 'graylog'
  become: true
  become_user: root
  tasks:
    - ansible.builtin.include_vars: 'group_vars/graylog.yml'
    - ansible.builtin.include_vars: 'group_vars/logging.yml'
    - ansible.builtin.import_tasks: 'roles/graylog/init.yml'
    - ansible.builtin.import_tasks: 'roles/graylog/setup_mongo.yml'
    - ansible.builtin.import_tasks: 'roles/graylog/setup_elasticsearch.yml'
    - ansible.builtin.import_tasks: 'roles/graylog/setup_graylog.yml'
    - ansible.builtin.import_tasks: 'roles/graylog/setup_nginx.yml'
    - ansible.builtin.import_tasks: 'roles/graylog/setup_ufw.yml'
