- hosts: 'rsyslog-agents'
  become: true
  become_user: root
  tasks:
    - ansible.builtin.include_vars: 'group_vars/graylog.yml'
    - ansible.builtin.include_vars: 'group_vars/logging.yml'
    - ansible.builtin.import_tasks: 'roles/rsyslog/setup_rsyslog.yml'
