####################################################################
# Apt update
####################################################################
- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: true

####################################################################
#  Setup Timedatectl
####################################################################
- name: Set time to {{ timezone }}
  ansible.builtin.shell: timedatectl set-ntp on && timedatectl set-timezone {{ timezone }}
