####################################################################
# Install/Setup Nginx
####################################################################
- name: Install/Setup Nginx
  ansible.builtin.package:
    name: '{{ item }}'
    state: latest
  with_items:
    - nginx

- name: Backup nginx conf
  ansible.builtin.shell: cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

- file:
    path: /etc/nginx/ssl
    owner: root
    group: root
    state: directory

- file:
    path: /etc/nginx/ssl
    state: directory
    mode: "0400"

- name: Copy nginx.conf
  ansible.builtin.template:
    src: conf/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Copy nginx_grr.conf
  ansible.builtin.template:
    src: conf/nginx/nginx_grr.conf
    dest: /etc/nginx/conf.d/nginx_grr.conf

- name: Generate DH key
  ansible.builtin.stat:
    path: /etc/nginx/ssl/dhparam.pem
  register: stat_dhparam
- shell: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
  when: not stat_dhparam.stat.exists
- shell: |
    openssl req -new -nodes -x509 -days 3650 \
    -subj "/C={{ cert_country }}/ST={{ cert_state }}/L={{ cert_local }}/O={{ cert_org }}/CN={{ grr_hostname }}.{{ base_domain }}" \
    -keyout /etc/nginx/ssl/{{ cert_name }}.key \
    -out /etc/nginx/ssl/{{ cert_name }}.crt
  when: not stat_dhparam.stat.exists

- name: Start Nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
