####################################################################
# Apt update
####################################################################
- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: true


####################################################################
# Install/Setup Splunk
####################################################################


####################################################################
# Install/Setup NGINX
####################################################################


####################################################################
# Setup UFW
####################################################################
