---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-json
        exclude: |
          (?x)(
            splunk-custom-search-command-python/sample_logs/zeek_conn.json|
            splunk-custom-search-command-python/sample_logs/zeek_files.json|
          )
      - id: check-shebang-scripts-are-executable
        exclude: |
          (?x)(
            kolide-docker/conf/kolide/entrypoint.sh|
            HashicorpBoundary/conf/docker/boundary-worker-swarm-entrypoint.sh|
            suricatav5-pf_ring/conf/suricata/suricata-pf_ring-init.sh|
          )
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: check-yaml
        exclude: |
          (?x)(
            ElasticStackv7/conf/filebeat/filebeat.yml|
            ksql-osquery-zeek-correlator/conf/windows-filebeat/filebeat.yml|
            ksql-osquery-zeek-suricata-correlator/conf/windows-filebeat/filebeat.yml|
            docker-compose.yml|
            kafka-enricher/docker-compose-kafka.yml|
            suricatav5-pf_ring/conf/suricata/suricata.yaml|
            kolide-docker/conf/osquery/osquery.yml|
            Kolide/roles/agents/deploy_osquery_centos.yml|
            Kolide/conf/filebeat/filebeat.yml|
          )
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        exclude: |
          (?x)(
            databricks-btv-dc30/data/chroma_btv_dc30_index.tar|
            databricks-btv-dc30/data/vector_docs.zip
          )
      - id: check-docstring-first
      - id: requirements-txt-fixer


  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black


  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8


  - repo: https://github.com/PyCQA/pylint
    rev: v3.1.0
    hooks:
      - id: pylint


  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      #  A quick check for the `eval()` built-in function
      - id: python-no-eval
      # A quick check for the deprecated `.warn()` method of python loggers
      - id: python-no-log-warn


  - repo: https://github.com/ansible/ansible-lint
    rev: v24.2.3
    hooks:
      - id: ansible-lint


  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.89.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
