- name: Allow OpenSSH
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Allow Boundary API access
  community.general.ufw:
    rule: allow
    port: '9200'
    proto: tcp

- name: Allow Boundary worker access
  community.general.ufw:
    rule: allow
    port: '9202'
    proto: tcp

- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: allow
