# STAGE: base
## Compiles Sliver for use
FROM golang:latest AS base

ARG SLIVER_VERSION=1.6.0

### Base packages
RUN apt-get update --fix-missing && apt-get -y install \
    git build-essential zlib1g zlib1g-dev wget zip unzip

### Add sliver user
RUN groupadd -g 999 sliver && useradd -r -u 999 -g sliver sliver
RUN mkdir -p /home/sliver/ && chown -R sliver:sliver /home/sliver

### Build sliver:
RUN mkdir -p /go/src/github.com/bishopfox/sliver
WORKDIR /go/src/github.com/bishopfox/sliver
ADD https://github.com/BishopFox/sliver.git /go/src/github.com/bishopfox/sliver/
#RUN make
RUN make VERSION=${SLIVER_VERSION}
RUN cp -vv sliver-server /opt/sliver-server
RUN cp -vv sliver-client /opt/sliver-client

# STAGE: test
## Run unit tests against the compiled instance
## Use `--target test` in the docker build command to run this stage
FROM base AS test

RUN apt-get update --fix-missing \
    && apt-get -y upgrade \
    && apt-get -y install \
    curl

RUN /opt/sliver-server unpack --force

### Run unit tests
RUN /go/src/github.com/bishopfox/sliver/go-tests.sh

######################################################## teamserver ########################################################
FROM debian:bookworm-slim AS teamserver

### Install production packages
RUN apt-get update --fix-missing \
    && apt-get -y upgrade \
    && apt-get -y install \
    libxml2 libxml2-dev libxslt-dev locate gnupg \
    libreadline6-dev libcurl4-openssl-dev git-core \
    libssl-dev libyaml-dev openssl autoconf libtool \
    ncurses-dev bison curl xsel postgresql \
    postgresql-contrib postgresql-client libpq-dev \
    curl libapr1 libaprutil1 libsvn1 \
    libpcap-dev libsqlite3-dev libgmp3-dev \
    nasm

### Install MSF for stager generation
RUN curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall \
    && chmod 755 msfinstall \
    && ./msfinstall \
    && mkdir -p ~/.msf4/ \
    && touch ~/.msf4/initial_setup_complete

### Cleanup unneeded packages
RUN apt-get remove -y curl gnupg \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

### Add sliver user
RUN groupadd -g 999 sliver \
    && useradd -r -u 999 -g sliver sliver \
    && mkdir -p /home/sliver/ \
    && chown -R sliver:sliver /home/sliver \
    && su -l sliver -c 'mkdir -p ~/.msf4/ && touch ~/.msf4/initial_setup_complete'

### Copy compiled binary
COPY --from=base /opt/sliver-server /opt/sliver-server
COPY --from=base /opt/sliver-client /opt/sliver-client

### Unpack Sliver:
RUN mkdir /configs && chown sliver:sliver /configs
RUN mkdir /payloads && chown sliver:sliver /payloads
USER sliver
RUN /opt/sliver-server unpack --force

###
COPY --chown=sliver:sliver conf/teamserver/server.json /home/sliver/.sliver/configs/server.json

WORKDIR /home/sliver/
EXPOSE 31337
VOLUME [ "/home/sliver", "/payloads", "/configs" ]
CMD /opt/sliver-server daemon & tail -f /home/sliver/.sliver/logs/sliver.log

######################################################## client ########################################################

FROM debian:bookworm-slim AS client

ENV OPERATOR_CONFIG=/configs/client_docker.cfg

### Copy sliver
COPY --from=base /opt/sliver-client /opt/sliver-client

### Add sliver user
RUN groupadd -g 999 sliver \
    && useradd -r -u 999 -g sliver sliver \
    && mkdir -p /home/sliver/ \
    && chown -R sliver:sliver /home/sliver

USER sliver
WORKDIR /home/sliver/
VOLUME [ "/home/sliver", "/payloads", "/configs" ]
CMD [ "/bin/bash" ]

######################################################## builder-linux ########################################################
FROM debian:bookworm-slim AS builder-linux

ENV OPERATOR_CONFIG=/configs/builder_linux.cfg

# https://sliver.sh/docs?name=Cross-compiling+Implants
RUN apt-get update -y && \
    apt-get install -y build-essential git

### Copy sliver
COPY --from=base /opt/sliver-server /opt/sliver-server


COPY conf/builders/entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

### Add sliver user
RUN groupadd -g 999 sliver \
    && useradd -r -u 999 -g sliver sliver \
    && mkdir -p /home/sliver/ \
    && chown -R sliver:sliver /home/sliver

USER sliver
RUN /opt/sliver-server unpack --force
WORKDIR /home/sliver/
VOLUME ["/home/sliver","/builders", "/payloads", "/config"]
ENTRYPOINT [ "/entrypoint.sh" ]

######################################################## builder-windows ########################################################
FROM debian:bookworm-slim AS builder-windows

ENV OPERATOR_CONFIG=/configs/builder_windows.cfg

# https://sliver.sh/docs?name=Cross-compiling+Implants
RUN apt-get update -y && \
    apt-get install -y libssl-dev cmake \
    liblzma-dev libxml2-dev patch clang zlib1g-dev \
    mingw-w64 gcc-mingw-w64-i686 openssl ca-certificates \
    build-essential binutils-mingw-w64 g++-mingw-w64 \
    gcc-mingw-w64-x86-64 git -y

### Download sliver
COPY --from=base /opt/sliver-server /opt/sliver-server

COPY conf/builders/entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

### Add sliver user
RUN groupadd -g 999 sliver \
    && useradd -r -u 999 -g sliver sliver \
    && mkdir -p /home/sliver/ \
    && chown -R sliver:sliver /home/sliver

USER sliver
RUN /opt/sliver-server unpack --force
WORKDIR /home/sliver/
VOLUME ["/home/sliver","/builders", "/payloads", "/config"]
ENTRYPOINT [ "/entrypoint.sh" ]
