######################################################################## base ########################################################################
FROM debian:bookworm-slim AS base

ARG SLIVER_VERSION=1.5.43

ADD https://github.com/BishopFox/sliver/releases/download/v${SLIVER_VERSION}/sliver-server_linux /opt/sliver-server
RUN chmod 755 /opt/sliver-server

ADD https://github.com/BishopFox/sliver/releases/download/v${SLIVER_VERSION}/sliver-client_linux /opt/sliver-client
RUN chmod 755 /opt/sliver-client

######################################################################## teamserver ########################################################################
FROM debian:bookworm-slim AS teamserver

### Install production packages
RUN apt-get update --fix-missing \
    && apt-get -y upgrade \
    && apt-get -y install \
    libxml2 libxml2-dev libxslt-dev locate gnupg \
    libreadline6-dev libcurl4-openssl-dev git-core \
    libssl-dev libyaml-dev openssl autoconf libtool \
    ncurses-dev bison curl xsel postgresql \
    postgresql-contrib postgresql-client libpq-dev \
    curl libapr1 libaprutil1 libsvn1 \
    libpcap-dev libsqlite3-dev libgmp3-dev \
    nasm netcat-openbsd

### Install MSF for stager generation
RUN curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall \
    && chmod 755 msfinstall \
    && ./msfinstall \
    && mkdir -p ~/.msf4/ \
    && touch ~/.msf4/initial_setup_complete

### Cleanup unneeded packages
RUN apt-get remove -y curl gnupg \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

### Add sliver user
RUN groupadd -g 999 sliver \
    && useradd -r -u 999 -g sliver sliver \
    && mkdir -p /home/sliver/ \
    && chown -R sliver:sliver /home/sliver \
    && su -l sliver -c 'mkdir -p ~/.msf4/ && touch ~/.msf4/initial_setup_complete'

### copy sliver client and server
COPY --from=base /opt/sliver-server /opt/sliver-server
COPY --from=base /opt/sliver-client /opt/sliver-client

### Unpack Sliver:
RUN mkdir /configs && chown 999:999 /configs
RUN mkdir /payloads && chown 999:999 /payloads
USER sliver
RUN /opt/sliver-server unpack --force

###
COPY --chown=sliver:sliver conf/teamserver/server.json /home/sliver/.sliver/configs/server.json

WORKDIR /home/sliver/
EXPOSE 31337
VOLUME [ "/home/sliver", "/payloads", "/configs" ]
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \
  CMD pgrep -f sliver-server && nc -z localhost 31337 || exit 1
CMD /opt/sliver-server daemon & tail -f /home/sliver/.sliver/logs/sliver.log

######################################################################## client ########################################################################
FROM debian:bookworm-slim AS client

ENV OPERATOR_CONFIG=/configs/client_docker.cfg

### copy sliver client
COPY --from=base /opt/sliver-client /opt/sliver-client

### Add sliver user
RUN groupadd -g 999 sliver \
    && useradd -r -u 999 -g sliver sliver \
    && mkdir -p /home/sliver/ \
    && chown -R sliver:sliver /home/sliver

USER sliver
WORKDIR /home/sliver/
VOLUME [ "/home/sliver", "/payloads", "/configs" ]
CMD ["/bin/bash"]

######################################################################## builder-linux ########################################################################
FROM debian:bookworm-slim AS builder-linux

ENV OPERATOR_CONFIG=/configs/builder_linux.cfg

# https://sliver.sh/docs?name=Cross-compiling+Implants
RUN apt-get update -y && apt-get install -y build-essential git


### copy sliver server
COPY --from=base /opt/sliver-server /opt/sliver-server
COPY conf/builders/entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

### Add sliver user
RUN groupadd -g 999 sliver \
    && useradd -r -u 999 -g sliver sliver \
    && mkdir -p /home/sliver/ \
    && chown -R sliver:sliver /home/sliver

USER sliver
RUN /opt/sliver-server unpack --force
WORKDIR /home/sliver/
VOLUME ["/home/sliver","/builders", "/payloads", "/config"]
ENTRYPOINT [ "/entrypoint.sh" ]

######################################################################## builder-windows ########################################################################
FROM debian:bookworm-slim AS builder-windows

ENV OPERATOR_CONFIG=/configs/builder_windows.cfg

# https://sliver.sh/docs?name=Cross-compiling+Implants
# https://sliver.sh/docs?name=Cross-compiling+Implants
RUN apt-get update -y && \
    apt-get install -y libssl-dev cmake \
    liblzma-dev libxml2-dev patch clang zlib1g-dev \
    mingw-w64 gcc-mingw-w64-i686 openssl ca-certificates \
    build-essential binutils-mingw-w64 g++-mingw-w64 \
    gcc-mingw-w64-x86-64 git -y

### copy sliver server
COPY --from=base /opt/sliver-server /opt/sliver-server
COPY conf/builders/entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

### Add sliver user
RUN groupadd -g 999 sliver \
    && useradd -r -u 999 -g sliver sliver \
    && mkdir -p /home/sliver/ \
    && chown -R sliver:sliver /home/sliver

USER sliver
RUN /opt/sliver-server unpack --force
WORKDIR /home/sliver/
VOLUME ["/home/sliver","/builders", "/payloads", "/config"]
ENTRYPOINT [ "/entrypoint.sh" ]
