---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
  namespace: ceph-csi-cephfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: k8s-cephfs-sc
