#########################################################
# Install/Setup Osquery
#########################################################
- name: Add APT GPG key for Osquery
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ osquery_gpg_key }}"

- name: Add Osquery repo
  ansible.builtin.apt_repository:
    repo: "{{ osquery_repo_url }}"
    state: present

- name: Install Osquery
  ansible.builtin.apt:
    name: osquery
    state: present

- name: Write Kolide public certificate contents to disk
  ansible.builtin.copy:
    content: "{{ kolide_public_cert }}"
    dest: "/etc/osquery/kolide.crt"
    mode: "0644"

- name: Sets permissions for /etc/osquery/kolide.crt
  ansible.builtin.file:
    path: '/etc/osquery/kolide.crt'
    owner: root
    group: root
    mode: "0644"

- name: Write Osquery enroll secret to disk
  ansible.builtin.copy:
    content: "{{ osquery_enroll_secret }}"
    dest: "/etc/osquery/osquery.key"
    mode: "0400"

- name: Sets permissions for /etc/osquery/osquery.key
  ansible.builtin.file:
    path: '/etc/osquery/osquery.key'
    owner: root
    group: root
    mode: "0644"

- name: Copy Osquery flags file
  ansible.builtin.template:
    src: 'conf/osquery/osquery.flags'
    dest: '/etc/osquery/osquery.flags'
    owner: root
    group: root
    mode: "0644"

- name: Restart Osquery
  ansible.builtin.service:
    name: 'osqueryd'
    state: restarted
    enabled: true
