####################################################################
# Setup hostname
####################################################################
- name: Set hostname
  ansible.builtin.hostname:
    name: '{{ hostname }}.{{ base_domain }}'

- name: Set hostname in /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ hostname }}'
    state: present

####################################################################
#  Setup Timedatectl
####################################################################
- name: Set time to {{ timezone }}
  community.general.timezone:
    name: '{{ timezone }}'

####################################################################
# Apt update
####################################################################
- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: true

- name: Update all packages to the latest version
  ansible.builtin.apt:
    upgrade: dist

####################################################################
# Reboot
####################################################################
- name: Reboot a slow machine that might have lots of updates to apply
  ansible.builtin.reboot:
    reboot_timeout: 3600

####################################################################
# Install software
####################################################################
- name: Install software
  ansible.builtin.package:
    name: '{{ item }}'
    state: latest
  with_items:
    - apt-transport-https
    - htop
    - tcpdump
    - net-tools
