services:
  ################################################# superset #################################################
  superset:
    container_name: superset
    build:
      context: .
      dockerfile: docker/Dockerfile-superset
    restart: unless-stopped
    environment:
      SUPERSET_SECRET_KEY: your-very-secure-random-key
    ports:
      - 8088:8088
    networks:
      - default
      - hive-backend
    volumes:
      - superset-data:/app/superset_home
    depends_on:
      - trino
      - metastore
      - minio

  ############################################# trino #############################################
  trino:
    container_name: trino
    build:
      context: .
      dockerfile: docker/Dockerfile-trino
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - default
      - hive-backend
    environment:
      - METASTORE_URI=thrift://metastore:9083
      - MINIO_URI=http://minio:9000
      - MINIO_ACCESS_KEY=minio_access_key
      - MINIO_SECRET_KEY=minio_secret_key
    volumes:
      - trino-data:/data/trino
    depends_on:
      - metastore

  ############################################# Metastore #############################################
  metastore:
    container_name: metastore
    build:
      context: .
      dockerfile: docker/Dockerfile-metastore
    restart: unless-stopped
    environment:
      - SERVICE_NAME=metastore
      - DB_DRIVER=postgres
      - HIVE_LOG_LEVEL=INFO
    networks:
      - hive-backend
    volumes:
      - metastore-data:/opt/hive
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
      - POSTGRES_DB=metastore
    networks:
      - hive-backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

  ################################################# minio #################################################
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    ports:
      - 9000:9000   # API
      - 9001:9001 # console
    networks:
      - default
      - hive-backend
    volumes:
      - minio-data:/data


networks:
  hive-backend:

volumes:
  metastore-data:
  trino-data:
  superset-data:
  minio-data:
  postgres-data:
