####################################################################
# Install Rsyslog
####################################################################
- name: Add '{{ rsyslog_ppa }}'
  ansible.builtin.apt_repository:
    repo: '{{ rsyslog_ppa }}'
    state: present

- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: true

- name: Install Rsyslog
  ansible.builtin.package:
    name: '{{ item }}'
    state: latest
  with_items:
    - rsyslog
    - rsyslog-mmjsonparse

- name: Backup of Rsyslog.conf
  ansible.builtin.copy:
    src: '/etc/rsyslog.conf'
    dest: '/etc/rsyslog.conf.bak'
    owner: root
    group: root
    mode: "0400"
    remote_src: true

- name: Copy Rsyslog.conf
  ansible.builtin.template:
    src: 'conf/rsyslog/rsyslog.conf'
    dest: '/etc/rsyslog.conf'
    owner: root
    group: root
    mode: "0400"

####################################################################
# Setup Rsyslog
####################################################################
- name: Copy 30-nginx.conf
  ansible.builtin.template:
    src: 'conf/rsyslog/30-nginx.conf'
    dest: '/etc/rsyslog.d/30-nginx.conf'
    owner: root
    group: root
    mode: "0400"

- name: Start Rsyslog client
  ansible.builtin.service:
    name: rsyslog
    state: restarted
    enabled: true
