################################################################
# Install prereqs
################################################################
- name: Install prereqs
  ansible.builtin.package:
    name: '{{ item }}'
    state: latest
  with_items:
    - 'cmake'
    - 'make'
    - 'gcc'
    - 'g++'
    - 'flex'
    - 'bison'
    - 'libpcap-dev'
    - 'libssl-dev'
    - 'python-dev'
    - 'swig'
    - 'zlib1g-dev'
    - 'libgeoip-dev'
    - 'build-essential'
    - 'libelf-dev'

################################################################
# Compile PF_RING
################################################################
- name: Git pull PF_RINT
  ansible.builtin.git:
    repo: '{{ pf_ring_url }}'
    dest: '{{ pf_ring_dir }}'

- name: PF_RING/kernel
  ansible.builtin.shell: '{{ item }}'
  args:
    chdir: '{{ pf_ring_dir }}/kernel'
  with_items:
    - 'make'
    - 'insmod ./pf_ring.ko'
  ignore_errors: true

- name: Make PF_RING/userland
  ansible.builtin.shell: '{{ item }}'
  args:
    chdir: '{{ pf_ring_dir }}/userland'
  with_items:
    - 'make'

- name: Make PF_RING/userland/lib
  ansible.builtin.shell: '{{ item }}'
  args:
    chdir: '{{ pf_ring_dir }}/userland/lib'
  with_items:
    - './configure --prefix={{ pf_ring_dir }}'
    - 'make install'

- name: Make PF_RING/userland/libpcap
  ansible.builtin.shell: '{{ item }}'
  args:
    chdir: '{{ pf_ring_dir }}/userland//libpcap'
  with_items:
    - './configure --prefix={{ pf_ring_dir }}'
    - 'make install'

- name: Make PF_RING/userland/tcpdump
  ansible.builtin.shell: '{{ item }}'
  args:
    chdir: '{{ pf_ring_dir }}/userland/tcpdump'
  with_items:
    - './configure --prefix={{ pf_ring_dir }}'
    - 'make install'

- name: Make PF_RING/kernel
  ansible.builtin.shell: '{{ item }}'
  args:
    chdir: '{{ pf_ring_dir }}/kernel'
  with_items:
    - 'make'
    - 'make install'

################################################################
# Add pf_ring on boot
################################################################
- name: Add pf_ring on boot
  ansible.builtin.lineinfile:
    path: '/etc/modules'
    line: 'pf_ring'
    create: true
    mode: "0750"
