####################################################################
# Install software
####################################################################
- name: Install dependencies for Zeek
  ansible.builtin.package:
    name: '{{ item }}'
    state: latest
  with_items:
    - cmake
    - make
    - gcc
    - g++
    - flex
    - bison
    - libpcap-dev
    - libssl-dev
    - python-dev
    - swig
    - zlib1g-dev

####################################################################
# Download Zeek source code
####################################################################
- name: Stat Zeek
  ansible.builtin.stat:
    path: '{{ zeek_base }}/bin/bro'
  register: zeek_compile

- name: Download Zeek source code
  ansible.builtin.git:
    repo: https://github.com/zeek/zeek
    recursive: true
    dest: '/tmp/zeek'
  when: not zeek_compile.stat.exists

####################################################################
# Install/Setup GeoIP
#
# If you see an error message similar to “Bro was not configured for GeoIP support”,
# then you need to rebuild Bro and make sure it is linked against libmaxminddb. Normally,
# if libmaxminddb is installed correctly then it should automatically be found when
# building Bro. If this doesn’t happen, then you may need to specify the path to the
# libmaxminddb installation (e.g. ./configure --with-geoip=<path>).
#
# https://docs.zeek.org/en/stable/frameworks/geoip.html
####################################################################
- name: Stat GeoIP database
  ansible.builtin.stat:
    path: '/usr/share/GeoIP/GeoLite2-City.mmdb'
  register: geoip_db
  when: zeek_geoip

- name: Install libmaxminddb
  ansible.builtin.package:
    name: '{{ item }}'
    state: latest
  with_items:
    - libmaxminddb-dev
  when: zeek_geoip

- name: Download and extract GeoIP database
  ansible.builtin.unarchive:
    src: '{{ zeek_geoip_db_url }}'
    dest: '/usr/share/GeoIP/'
    remote_src: true
    extra_opts: [--strip-components=1]
  when: not geoip_db.stat.exists and zeek_geoip

####################################################################
# Compile Zeek from source
####################################################################
- name: Debug msg
  ansible.builtin.debug:
    msg: 'WARNING - Compiling Zeek from source can take up to 30mins'
  when: not zeek_compile.stat.exists

- name: Compile Zeek from source
  ansible.builtin.shell: '{{ item }}'
  args:
    chdir: '/tmp/zeek'
  with_items:
    - './configure --with-pcap={{ pf_ring_dir }} --prefix={{ zeek_base }}/'
    - 'make'
    - 'make install'
  when: not zeek_compile.stat.exists

- name: Test GeoIP
  ansible.builtin.shell: './bro -e "print lookup_location(8.8.8.8);"'
  args:
    chdir: '{{ zeek_base }}/bin'
  when: zeek_geoip

####################################################################
# Create Zeek user and set perms
####################################################################
- name: Create Zeek user
  ansible.builtin.user:
    name: '{{ zeek_user }}'
    shell: /usr/sbin/nologin
    home: '{{ zeek_base }}'

- name: Permissions 'setcap cap_net_raw,cap_net_admin=eip {{ zeek_base }}/bin/bro'
  community.general.capabilities:
    path: '{{ zeek_base }}/bin/bro'
    capability: '{{ item }}'
    state: present
  with_items:
    - 'cap_net_raw+eip'
    - 'cap_net_admin+eip'

- name: Set Zeek base dir perms
  ansible.builtin.file:
    path: '{{ zeek_base }}'
    owner: '{{ zeek_user }}'
    group: '{{ zeek_user }}'
    recurse: true

- name: Add Zeek to system-wide $PATH
  ansible.builtin.copy:
    dest: /etc/profile.d/zeek-path.sh
    content: 'PATH=$PATH:{{ zeek_base }}/bin'
    mode: "0750"

####################################################################
# Configure Zeek
####################################################################
- name: 'Copy Zeek configs'
  ansible.builtin.template:
    src: 'conf/zeek/{{ item }}'
    dest: '{{ zeek_base }}/etc/{{ item }}'
    mode: "0640"
    owner: '{{ zeek_user }}'
    group: '{{ zeek_user }}'
  with_items:
    - 'networks.cfg'
    - 'node.cfg'

- name: Replace Zeek e-mail
  ansible.builtin.lineinfile:
    path: '{{ zeek_base }}/etc/broctl.cfg'
    regexp: '^MailTo ='
    line: 'MailTo = {{ zeek_mail_to }}'

- name: Enable Bro logging in JSON format
  ansible.builtin.lineinfile:
    path: '{{ zeek_base }}/share/bro/site/local.bro'
    line: '{{ item }}'
  with_items:
    - '# Enable Bro logging in JSON format'
    - 'redef LogAscii::json_timestamps = JSON::TS_ISO8601;'
    - 'redef LogAscii::use_json = T;'

- name: Create scripts directory for custom Zeek scripts
  ansible.builtin.file:
    path: '{{ zeek_base }}/share/bro/scripts'
    state: directory
    mode: "0775"
    owner: '{{ zeek_user }}'
    group: '{{ zeek_user }}'

####################################################################
# Zeek scripts
####################################################################
- name: Enable Zeek file extraction
  ansible.builtin.lineinfile:
    path: '{{ zeek_base }}/share/bro/site/local.bro'
    line: '{{ item }}'
  with_items:
    - '# Zeek file extraction'
    - '@load policy/frameworks/files/extract-all-files.bro'
  when: zeek_file_extraction

- name: Enable Zeek stats
  ansible.builtin.lineinfile:
    path: '{{ zeek_base }}/share/bro/site/local.bro'
    line: '{{ item }}'
  with_items:
    - '# Zeek stats'
    - '@load policy/misc/stats.bro'
  when: zeek_stats

- name: Copy custom Zeek scripts
  ansible.builtin.template:
    src: "{{ item }}"
    dest: '{{ zeek_base }}/share/bro/scripts/{{ item | basename }}'
    mode: "0640"
    owner: '{{ zeek_user }}'
    group: '{{ zeek_user }}'
  with_fileglob:
    - 'conf/zeek/scripts/*'
  when: zeek_custom_scripts

- name: Add commnet for custom scripts
  ansible.builtin.lineinfile:
    path: '{{ zeek_base }}/share/bro/site/local.bro'
    line: '# Zeek custom scripts'
  when: zeek_custom_scripts

- name: Enable Zeek file extraction
  ansible.builtin.lineinfile:
    path: '{{ zeek_base }}/share/bro/site/local.bro'
    line: '@load scripts/{{ item | basename }}'
  with_fileglob:
    - 'conf/zeek/scripts/*'
  when: zeek_custom_scripts

####################################################################
# Zeek deploy
####################################################################
- name: Run Bro deploy
  ansible.builtin.shell: '{{ zeek_base }}/bin/broctl {{ item }}'
  become: true
  become_user: '{{ zeek_user }}'
  with_items:
    - 'install'
    - 'deploy'
    - 'status'
