####################################################################
# Install/Setup Filebeat
####################################################################
- name: Add Elastic GPG key
  ansible.builtin.apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic repo
  ansible.builtin.apt_repository:
    repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
    state: present

- name: Install/Setup Elasticsearch
  ansible.builtin.package:
    name: '{{ item }}'
    state: latest
  with_items:
    - filebeat

- name: Filebeat.yml
  ansible.builtin.template:
    src: conf/filebeat/filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Start Filebeat service
  ansible.builtin.service:
    name: filebeat
    state: restarted
    enabled: true
