---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-load-balancer-external-access
  namespace: dvwa
spec:
  selector:
    app.kubernetes.io/name: dvwa
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
