- name: Install/Setup Rsyslog client
  hosts: 'rsyslog-client'
  become: true
  become_user: root
  tasks:
    - name: Import rsyslog variables
      ansible.builtin.include_vars: 'group_vars/logging.yml'
    - name: Install/Setup osquery
      ansible.builtin.import_tasks: 'roles/osquery/setup_osquery.yml'
    - name: Install/Setup Rsyslog client
      ansible.builtin.import_tasks: 'roles/rsyslog_client/setup_rsyslog.yml'
