- hosts: 'boundry_single_node'
  become: true
  become_user: root
  tasks:
    - ansible.builtin.include_vars: 'group_vars/boundary.yml'
    # - import_tasks: 'roles/init.yml'
    - ansible.builtin.import_tasks: 'roles/boundary/setup_postgres.yml'  # Install/Setup Postgres
    - ansible.builtin.import_tasks: 'roles/boundary/setup_boundary.yml'  # Install/Setup Boundary
    - ansible.builtin.import_tasks: 'roles/boundary/setup_ufw.yml'       # Setup firewall
