####################################################################
#  Setup Firewall
####################################################################
- name: Setup Ubuntu UFW firewall
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Allow HTTP for NGINX
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow HTTPS for NGINX
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Allow Filebeat for Graylog
  community.general.ufw:
    rule: allow
    port: '{{ graylog_beats_port }}'
    proto: tcp
  when: graylog_beats_logging

- name: Allow Syslog TCP for Graylog
  community.general.ufw:
    rule: allow
    port: '{{ graylog_syslog_tcp_port }}'
    proto: tcp
  when: graylog_syslog_tcp_logging

- name: Allow Syslog UDP for Graylog
  community.general.ufw:
    rule: allow
    port: '{{ graylog_syslog_udp_port }}'
    proto: tcp
  when: graylog_syslog_udp_logging

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming
