---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "block-file-inclusion"
spec:
  kprobes:
  - call: "fd_install"
    syscall: false
    args:
    - index: 0
      type: int
    - index: 1
      type: "file"
    selectors:
    - matchBinaries:
      - operator: "NotIn"
        values:
          - "/usr/bin/cat"
      matchArgs:
      - index: 1
        operator: "Prefix"
        values:
          - "/var/www/html/vulnerabilities/"

      matchActions:
      - action: Sigkill


---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "block-file-inclusion"
spec:
  kprobes:
  - call: "fd_install"
    syscall: false
    args:
    - index: 0
      type: int
    - index: 1
      type: "file"
    selectors:
    - matchPIDs:
      - operator: "In"
        followForks: false
        isNamespacePID: true
        values:
        - 0
        - 1
      matchArgs:
      - index: 1
        operator: "Prefix"
        values:
          - "/etc/"
      matchActions:
      - action: Sigkill
