---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: "example-uprobe"
  namespace: "dvwa"
# spec:
#   uprobes:
#   - path: "/lib64/libc.so.6"
#     symbols:
#     - "malloc"
#     selectors:
#     - matchBinaries:
#       - operator: "In"
#         values:
#         - "/usr/bin/bash"
# # spec:
#   uprobes:
#   - path: "/opt/bitnami/mysql/bin/mysqld"
#     symbols:
#     - "mysql_real_query"
#     - "mysql_real_query_nonblocking"
#     - "mysql_send_query"
#     - "mysql_send_query_nonblocking"
# ---
# apiVersion: cilium.io/v1alpha1
# kind: TracingPolicy
# metadata:
#   name: "file-all"

spec:
  kprobes:
  - call: "sys_rename"
    syscall: true
    #return: true
    args:
    - index: 0
      type: "string"
    - index: 1
      type: "string"
    # returnArg:
    #   index: 0
    #   type: "int"
    #returnArgAction: "Post"
    selectors:
    # - matchPIDs:
    #   - operator: In
    #     followForks: true
    #     isNamespacePID: true
    #     values:
    #     - 1
    - matchArgs:
      - index: 1
        operator: "Prefix"
        values:
          - "../../hackable/uploads"
      matchActions:
      - action: Override
        argError: -
      #- action: Signal
      #  argSig: 0
      #- action: Post


  # - call: "fd_install"
  #   syscall: false
  #   args:
  #   - index: 0
  #     type: int
  #   - index: 1
  #     type: "file"
  #   selectors:
  #   # - matchPIDs:
  #   #   - operator: NotIn
  #   #     followForks: true
  #   #     isNamespacePID: true
  #   #     values:
  #   #     - 1
  #   - matchArgs:
  #     - index: 1
  #       operator: "Prefix"
  #       values:
  #       - "/var/www/html/hackable/uploads"
  #     matchActions:
  #     - action: FollowFD
  #       argFd: 0
  #       argName: 1
  # - call: "sys_write"
  #   syscall: true
  #   args:
  #   - index: 0
  #     type: "fd"
  #   - index: 1
  #     type: "char_buf"
  #     sizeArgIndex: 3
  #   - index: 2
  #     type: "size_t"
  #   returnArgAction: "Post"
  #   selectors:
  #   # - matchPIDs:
  #   #   - operator: NotIn
  #   #     followForks: true
  #   #     isNamespacePID: true
  #   #     values:
  #   #     - 1
  #   - matchArgs:
  #     - index: 0
  #       operator: "Prefix"
  #       values:
  #       - "/var/www/html/hackable/uploads"
  #     matchActions:
  #     - action: Sigkill
