cilium:
  namespace: cilium
  operator:
    replicas: 1
  ipam:
    operator:
      clusterPoolIPv4PodCIDRList: 10.42.0.0/16
  ipv4NativeRoutingCIDR: 10.42.0.0/16
  ipv4:
    enabled: true
  loadBalancer:
    mode: dsr
  routingMode: native
  autoDirectNodeRoutes: true
  hubble:
    relay:
      enabled: true
    ui:
      enabled: true
  l2announcements:
    enabled: true
  kubeProxyReplacement: "strict"

tetragon:
  namespace: kube-system

dvwa:
  namespace: dvwa
  replicaCount: 1
  ingress:
    enabled: false
  volumes:
  - name: config
    configMap:
      name: dvwa

  # Additional volumeMounts on the output Deployment definition.
  volumeMounts:
    - name: config
      mountPath: "/var/www/html/config"

mysql:
  enabled: true
  architecture: standalone
  auth:
    createDatabase: true
    database: dvwa
    username: dvwa
    existingSecret: mysql
