dvwa:
  replicaCount: 1
  ingress:
    enabled: false
  volumes:
  - name: config
    configMap:
      name: dvwa

  # Additional volumeMounts on the output Deployment definition.
  volumeMounts:
    - name: config
      mountPath: "/var/www/html/config"

mysql:
  enabled: true
  architecture: standalone
  auth:
    createDatabase: true
    database: dvwa
    username: dvwa
    existingSecret: mysql
