####################################################################
#  Setup Firewall
####################################################################
- name: Setup Ubuntu UFW firewall
  community.general.ufw:
    rule: allow
    name: OpenSSH
- community.general.ufw:
    rule: allow
    port: 80
    proto: tcp
- community.general.ufw:
    rule: allow
    port: 443
    proto: tcp
- community.general.ufw:
    rule: allow
    proto: tcp
    port: 8888
- community.general.ufw:
    state: enabled
    policy: deny
