####################################################################
# Install/Setup MongoDB
####################################################################
- name: Install MongoDB
  ansible.builtin.package:
    name: '{{ item }}'
    state: latest
  with_items:
    - mongodb-server

- name: Copy Mongo conf
  ansible.builtin.template:
    src: conf/mongo/mongodb.conf
    dest: /etc/mongodb.conf

- name: Start Mongo service
  ansible.builtin.service:
    name: mongodb
    state: restarted
    enabled: true
