- hosts: kolide
  become: true
  become_user: root
  tasks:
    - ansible.builtin.import_tasks: roles/init.yml
    - ansible.builtin.import_tasks: roles/kolide/redis.yml
    - ansible.builtin.import_tasks: roles/kolide/mysql.yml
    - ansible.builtin.import_tasks: roles/kolide/kolide.yml
    # - import_tasks: roles/kolide/filebeat.yml
