name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/release.yml'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Package charts
        run: |
          mkdir -p docs
          helm package charts/* -d docs

      - name: Package charts
        run: |
          mkdir -p docs
          helm package charts/* -d docs

      - name: Generate index.yaml
        run: |
          helm repo index docs --url https://cptofevilminions.github.io/BlogProjects

      - name: Commit and push chart repo to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
